services:
  ansible:
    image: alpine/ansible
    environment:
      - "ANSIBLE_HOST_KEY_CHECKING=False"
      - "ANSIBLE_CONFIG=/etc/ansible/ansible.cfg"
      - "GITHUB_URL=https://github.com/nbittich/app-swarm.git"
      - "DEPLOY_VERSION=0.2.0"
      - "DEPLOY_PATH=/data/swarm"
    volumes:
      - ./ssh_keys:/root/.ssh
      - ./playbooks:/apps
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./inventory:/inventory
      - ./sdata:/sdata
    working_dir: /apps
    entrypoint: ["tail", "-f", "/dev/null"]
