- name: Deploy docker project
  gather_facts: False
  hosts: cloud
  become: True
  vars:
    destination_path: '{{ lookup("env", "DEPLOY_PATH") }}'
    github_url: '{{ lookup("env", "GITHUB_URL")}}'
    deploy_version: '{{ lookup("env", "DEPLOY_VERSION")}}'
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: "{{ destination_path }}"
        state: directory
        mode: "0755"
    - name: Clone the GitHub repository
      git:
        repo: '{{ github_url }}'
        dest: "{{ destination_path }}"
        update: yes
        version: '{{ deploy_version }}'
    - name: Copy env files
      copy:
         src: /sdata/secrets
         dest: '{{ destination_path }}'
         mode: '0755'
    - name: Copy docker-compose.override.yml
      copy:
         src: /sdata/docker-compose.override.yml
         dest: '{{ destination_path }}/docker-compose.override.yml'
         mode: '0755'
    - name: Run docker compose up -d
      command:
        cmd:  docker compose up -d
        chdir: "{{ destination_path }}"

